services:
  - type: web
    name: cluesforyou
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python cluesforyou.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
